code --install-extension dbaeumer.vscode-eslint
code --install-extension github.codespaces
code --install-extension github.github-vscode-theme
code --install-extension visualstudioexptteam.vscodeintellicode 
code --install-extension vscodevim.vim
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack