code --install-extension dbaeumer.vscode-eslint
code --install-extension ms-azuretools.vscode-docker
code --install-extension eamodio.gitlens 
code --install-extension vscodevim.vim
code --install-extension obinbentley.sass-indented 
code --install-extension octref.vetur 
code --install-extension visualstudioexptteam.vscodeintellicode 
code --install-extension redhat.vscode-yaml 
code --install-extension ms-python.python
code --install-extension github.codespaces
code --install-extension rust-lang.rust
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack